"""LLM-driven driver synthesis from an ExplorationResult (gh#41).

`generate_driver` asks the LLM to synthesize a `drivers/<name>.md` from the
exploration log. The output is validated against required section markers
(ENVIRONMENT, PRIMARY TOOLS, PATTERNS, RESPONSE FORMAT, COMPLETION) anchored
to line start — substring matches in prose do not satisfy the check. The
auto-gen header is injected INSIDE the body, after the closing `---` of the
frontmatter, so `_parse_driver_frontmatter` in `llm/prompts.py` still finds
the YAML block at byte 0.
"""
from __future__ import annotations

import datetime as _dt
import logging
import os
import re
from typing import Optional

from llm import chat, get_client
from prompts import _DRIVERS_DIR

from .models import ExplorationResult
from .prompts import build_generation_prompt

log = logging.getLogger(__name__)

AUTO_GEN_HEADER_TEMPLATE = "<!-- Auto-generated by clive --explore on {date} -->"
AUTO_GEN_HEADER = "Auto-generated by clive --explore"

# Section markers — each must appear at the start of a line, optionally
# preceded by markdown heading tokens (#, ##, ...). Substring matches in
# prose do not satisfy these.
_REQUIRED_SECTIONS = (
    "ENVIRONMENT",
    "PRIMARY TOOLS",
    "PATTERNS",
    "RESPONSE FORMAT",
    "COMPLETION",
)
_SECTION_REGEXES = {
    section: re.compile(rf"^(?:#+\s+)?{re.escape(section)}\b", re.MULTILINE)
    for section in _REQUIRED_SECTIONS
}


def generate_driver(
    tool_name: str,
    result: ExplorationResult,
    client=None,
    model: Optional[str] = None,
) -> str:
    """Synthesize a driver from an exploration session.

    Returns the markdown text with an auto-gen header inserted INSIDE the
    body (after the frontmatter close) so frontmatter parsing at byte 0
    remains unaffected.

    Raises ValueError if the LLM output is missing required sections or
    lacks frontmatter entirely.
    """
    client = client if client is not None else get_client()
    prompt = build_generation_prompt(result)
    messages = [
        {"role": "system", "content": "You are clive's tool-discovery driver synthesizer."},
        {"role": "user", "content": prompt},
    ]
    text, _pt, _ct = chat(client, messages, model=model, max_tokens=1500)
    text = text.strip()

    _validate_driver_text(tool_name, text)
    return _inject_header(text)


def _validate_driver_text(tool_name: str, text: str) -> None:
    if not text.startswith("---"):
        raise ValueError(f"driver for {tool_name} missing frontmatter")
    front_end = text.find("---", 3)
    if front_end < 0:
        raise ValueError(f"driver for {tool_name} has malformed frontmatter")
    body = text[front_end + 3:]
    missing = [s for s, rx in _SECTION_REGEXES.items() if not rx.search(body)]
    if missing:
        raise ValueError(
            f"driver for {tool_name} missing section(s): {', '.join(missing)}"
        )


def _inject_header(text: str) -> str:
    """Insert the auto-gen header right after the closing `---` of the frontmatter."""
    front_end = text.find("---", 3)
    head = text[: front_end + 3]
    tail = text[front_end + 3:]
    header = AUTO_GEN_HEADER_TEMPLATE.format(date=_dt.date.today().isoformat())
    if tail.startswith("\n"):
        return f"{head}\n{header}{tail}"
    return f"{head}\n{header}\n{tail}"


# ─── Writer (task 5 piece — kept here so caller has one import target) ───


_SAFE_NAME = re.compile(r"\A[A-Za-z0-9_][A-Za-z0-9_.\-]*\Z")


def write_generated_driver(
    tool_name: str,
    driver_text: str,
    drivers_dir: Optional[str] = None,
    overwrite: bool = False,
) -> str:
    """Write a generated driver to ``drivers_dir/<tool>.md``.

    Refuses to overwrite an existing driver unless ``overwrite=True`` so
    hand-written drivers can't be clobbered. Validates ``tool_name``
    against an alphanumeric-plus-dot-dash pattern to prevent path traversal.
    """
    if not _SAFE_NAME.match(tool_name):
        raise ValueError(f"unsafe tool name for driver path: {tool_name!r}")
    base = drivers_dir if drivers_dir is not None else _DRIVERS_DIR
    os.makedirs(base, exist_ok=True)
    path = os.path.join(base, f"{tool_name}.md")
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(
            f"driver already exists at {path}; pass overwrite=True to replace"
        )
    with open(path, "w") as f:
        f.write(driver_text)
    return path
