"""LLM-driven driver synthesis from an ExplorationResult (gh#41).

`generate_driver` asks the LLM to synthesize a `drivers/<name>.md` from the
exploration log. The output is validated against required section markers
(ENVIRONMENT, PRIMARY TOOLS, PATTERNS, RESPONSE FORMAT, COMPLETION) anchored
to line start — substring matches in prose do not satisfy the check. The
auto-gen header is injected INSIDE the body, after the closing `---` of the
frontmatter, so `_parse_driver_frontmatter` in `llm/prompts.py` still finds
the YAML block at byte 0.
"""
from __future__ import annotations

import datetime as _dt
import logging
import os
import re
from typing import Optional

from llm import chat, get_client
from prompts import _DRIVERS_DIR

from .models import ExplorationResult
from .prompts import build_generation_prompt

log = logging.getLogger(__name__)

AUTO_GEN_HEADER_TEMPLATE = "<!-- Auto-generated by clive --explore on {date} -->"
AUTO_GEN_HEADER = "Auto-generated by clive --explore"

# Section markers — each must appear at the start of a line, optionally
# preceded by markdown heading tokens (#, ##, ...). Substring matches in
# prose do not satisfy these.
_REQUIRED_SECTIONS = (
    "ENVIRONMENT",
    "PRIMARY TOOLS",
    "PATTERNS",
    "PITFALLS",          # gh#41 debug Bug 4 — was previously omitted
    "RESPONSE FORMAT",
    "COMPLETION",
)
_SECTION_REGEXES = {
    section: re.compile(rf"^(?:#+\s+)?{re.escape(section)}\b", re.MULTILINE)
    for section in _REQUIRED_SECTIONS
}

# Strip fenced code blocks before scanning for section markers (gh#41 debug
# Bug 10). Otherwise a driver where the only ENVIRONMENT/PRIMARY TOOLS/etc.
# lines live inside a ```...``` decoy would pass validation while carrying
# no real content.
_FENCED_BLOCK = re.compile(r"```.*?```", re.DOTALL)


def generate_driver(
    tool_name: str,
    result: ExplorationResult,
    client=None,
    model: Optional[str] = None,
) -> str:
    """Synthesize a driver from an exploration session.

    Returns the markdown text with an auto-gen header inserted INSIDE the
    body (after the frontmatter close) so frontmatter parsing at byte 0
    remains unaffected.

    Raises ValueError if:
      - the exploration produced no usable signal (no successful probes
        AND no DONE summary) — refuses to hallucinate from nothing
        (gh#41 debug Bug 11);
      - the LLM output is missing required sections, has duplicates,
        is out of canonical order, or lacks frontmatter
        (gh#41 debug Bug 10).
    """
    # Empty-exploration guard — refuse to call the LLM if there's nothing
    # to base the synthesis on. The synthesizer prompt's "do not invent"
    # rule conflicts with its "MUST contain these sections" rule when zero
    # signal is present, and LLMs resolve by hallucinating.
    if result.success_count == 0 and not result.summary:
        raise ValueError(
            f"refusing to synthesize driver for {tool_name!r}: empty "
            f"exploration result (0 successful probes, no DONE summary)"
        )
    client = client if client is not None else get_client()
    prompt = build_generation_prompt(result)
    messages = [
        {"role": "system", "content": "You are clive's tool-discovery driver synthesizer."},
        {"role": "user", "content": prompt},
    ]
    text, _pt, _ct = chat(client, messages, model=model, max_tokens=1500)
    text = text.strip()

    _validate_driver_text(tool_name, text)
    return _inject_header(text)


def _validate_driver_text(tool_name: str, text: str) -> None:
    if not text.startswith("---"):
        raise ValueError(f"driver for {tool_name} missing frontmatter")
    front_end = text.find("---", 3)
    if front_end < 0:
        raise ValueError(f"driver for {tool_name} has malformed frontmatter")
    body = text[front_end + 3:]
    # Strip fenced code blocks so section markers inside ```...``` decoys
    # don't count as real sections (gh#41 debug Bug 10).
    body_no_fences = _FENCED_BLOCK.sub("", body)

    # Each required section must appear exactly once at line start, in
    # canonical order. Multiple occurrences create structural ambiguity
    # that downstream parsers resolve inconsistently; out-of-order
    # sections are a smell that suggests a non-template-conforming driver.
    missing: list[str] = []
    duplicates: list[str] = []
    positions: list[tuple[int, str]] = []
    for section, rx in _SECTION_REGEXES.items():
        hits = rx.findall(body_no_fences)
        if not hits:
            missing.append(section)
            continue
        if len(hits) > 1:
            duplicates.append(section)
            continue
        m = rx.search(body_no_fences)
        if m is not None:
            positions.append((m.start(), section))

    if missing:
        raise ValueError(
            f"driver for {tool_name} missing section(s): {', '.join(missing)}"
        )
    if duplicates:
        raise ValueError(
            f"driver for {tool_name} has duplicate section(s): "
            f"{', '.join(duplicates)}"
        )
    expected = [s for _, s in sorted(positions)]
    canonical = list(_REQUIRED_SECTIONS)
    if expected != canonical:
        raise ValueError(
            f"driver for {tool_name} sections out of canonical order: "
            f"got {expected}, expected {canonical}"
        )


def _inject_header(text: str) -> str:
    """Insert the auto-gen header right after the closing `---` of the frontmatter."""
    front_end = text.find("---", 3)
    head = text[: front_end + 3]
    tail = text[front_end + 3:]
    header = AUTO_GEN_HEADER_TEMPLATE.format(date=_dt.date.today().isoformat())
    if tail.startswith("\n"):
        return f"{head}\n{header}{tail}"
    return f"{head}\n{header}\n{tail}"


# ─── Writer (task 5 piece — kept here so caller has one import target) ───


# Tool-name regex (gh#41 debug Bug 2/6) — tightened to lowercase only and
# no dots, closing two earlier holes:
#   - uppercase names like ``RG`` collided with ``rg.md`` on case-insensitive
#     filesystems (macOS APFS default)
#   - dotted names like ``foo.md`` produced confusing filenames such as
#     ``drivers/foo.md.md`` and could match Windows-reserved patterns
_SAFE_NAME = re.compile(r"\A[a-z][a-z0-9_\-]*\Z")

# Reserved names — first-class hand-written drivers shipped in
# ``src/clive/drivers/``. Discovery must NOT overwrite these even with
# ``overwrite=True`` (gh#41 debug Bug 5). Most notably, ``explore`` is the
# meta-driver that drives exploration itself — overwriting it would brick
# all future ``--explore`` invocations.
RESERVED_NAMES = frozenset({
    "explore",
    "shell", "browser", "data", "docs",
    "default", "email", "email_cli", "agent",
    "media", "room",
})


def _check_tool_name(tool_name: str) -> None:
    """Raise ``ValueError`` if ``tool_name`` is unsafe or reserved.

    Centralised so the same guard fires at every pipeline entry point:
    ``handle_explore``, ``explore_tool``, and ``write_generated_driver``.
    Fail-fast at the top of the pipeline prevents an attacker-controlled
    name from spending LLM tokens and opening a tmux pane before the
    terminal write-time check finally rejects it.
    """
    if not _SAFE_NAME.match(tool_name):
        raise ValueError(f"unsafe tool name for driver path: {tool_name!r}")
    if tool_name in RESERVED_NAMES:
        raise ValueError(
            f"{tool_name!r} is a reserved driver name; refusing to overwrite "
            f"the core driver. Pick a different name."
        )


def write_generated_driver(
    tool_name: str,
    driver_text: str,
    drivers_dir: Optional[str] = None,
    overwrite: bool = False,
) -> str:
    """Write a generated driver to ``drivers_dir/<tool>.md``.

    Refuses to overwrite an existing driver unless ``overwrite=True`` so
    hand-written drivers can't be clobbered. Validates ``tool_name`` via
    ``_check_tool_name`` (regex + reserved-names guard).
    """
    _check_tool_name(tool_name)
    base = drivers_dir if drivers_dir is not None else _DRIVERS_DIR
    os.makedirs(base, exist_ok=True)
    path = os.path.join(base, f"{tool_name}.md")
    # Atomic write — fixes the TOCTOU race between os.path.exists() and
    # open(path, "w"). Non-overwrite uses O_EXCL ("x" mode) so only one
    # racer succeeds. Overwrite writes to a sibling tmp and renames; the
    # rename is atomic on POSIX, so concurrent readers never see an empty
    # or partially-written file (gh#41 debug Bug 3).
    if overwrite:
        tmp = f"{path}.tmp-{os.getpid()}"
        try:
            with open(tmp, "w") as f:
                f.write(driver_text)
            os.replace(tmp, path)
        except Exception:
            # Clean up the orphan tmp on failure.
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
    else:
        try:
            # "x" mode == O_CREAT | O_EXCL | O_WRONLY — atomic exists+create.
            with open(path, "x") as f:
                f.write(driver_text)
        except FileExistsError:
            raise FileExistsError(
                f"driver already exists at {path}; pass overwrite=True to replace"
            )
    return path
